### ISSUE TITLE
Does kPAR work under Java-8?

### ISSUE THREAD

**Issue by jose** [SerVal-DTF/FL-VS-APR#7]
Hi,

The [README.md](https://github.com/SerVal-DTF/FL-VS-APR/blob/master/kPAR/README.md) file mentions that kPAR requires Java-7, would it incorrect/wrong to run it under Java-8?

--
Best,
Jose

**Comment by Kui-Liu** [comment]
It dependents on the version of D4J.

**Comment by jose** [comment]
Ok.  So, if I use

- latest version of D4J v2.0.0 I can (perhaps should) use kPAR under Java-8

and if I use

- D4J v1.0.0 I can (perhaps should) use kPAR under Java-7

is that right?

**Comment by Kui-Liu** [comment]
Yes, you are right, because some Java-8 D4J bugs cannot be compiled successfully under Java-7.

If you want to use kPAR under Java-8, you should change these two lines: https://github.com/SerVal-DTF/FL-VS-APR/blob/master/kPAR/pom.xml#L86, https://github.com/SerVal-DTF/FL-VS-APR/blob/master/kPAR/pom.xml#L87

**Comment by jose** [comment]
Ok, thanks.
